language: go

go:
  - 1.8
  - master

matrix:
  allow_failures:
  - go: master

sudo: required

services:
  - docker

install:
 - make setup-ci

script:
  - make test

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile _build/coverage-all.out -service=travis-ci
  - /bin/bash -c '[ "$TRAVIS_BRANCH" == "master" ] && make build-linux-64'
  - /bin/bash -c '[ "$TRAVIS_BRANCH" == "master" ] && ./push_to_docker.sh && curl -H POST $TEST_FARM_URL'
