language: go

go:
  - 1.6.2
  - 1.7.0

sudo: required

services:
  - docker

install:
 - make setup-ci

before_script:
  - sleep 10

script:
  - make test

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile _build/coverage-all.out -service=travis-ci
  #- make cross
  #- ./push_to_docker.sh
  #- /bin/bash -c '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ] && curl -H POST $TEST_FARM_URL'
