language: go

go:
  - 1.7
  - master

matrix:
  allow_failures:
  - go: master

sudo: required

services:
  - docker

install:
 - make setup-ci

script:
  - make test

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile _build/coverage-all.out -service=travis-ci
  - make build-linux-64
  - ./push_to_docker.sh
  #- /bin/bash -c '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ] && curl -H POST $TEST_FARM_URL'
