postgres:
  user: "offers_test"
  dbName: "offers_test"
  host: "localhost"
  port: 8585
  sslMode: "disable"
  maxIdleConns: 10
  maxOpenConns: 10
cache:
  maxAgeSeconds: 43200
offersCache:
  maxAgeSeconds: 300
  cleanupInterval: 30
