postgres:
  user: "offers"
  dbName: "offers"
  host: "localhost"
  port: 8585
  sslMode: "disable"
  maxIdleConns: 10
  maxOpenConns: 10
newrelic:
  app: offers
  key:
cache:
  maxAgeSeconds: 43200
offersCache:
  maxAgeSeconds: 300
  cleanupInterval: 30
basicauth:
  username: user
  password: pass
pagination:
  limit: 50
  offset: 0
jaeger:
  disabled: true
  samplingProbability: 0.0001
extensions:
  dogstatsd:
    host: localhost:8125
    prefix: offers.