postgres:
  user: "offers_perf"
  dbName: "offers_perf"
  host: "localhost"
  port: 8585
  sslMode: "disable"
redis:
  host: localhost
  port: 6333
  password: ""
  db: 0
  maxPoolSize: 20
offersCache:
  maxAgeSeconds: 300
  cleanupInterval: 30
