postgres:
  user: "offers_test"
  dbName: "offers_test"
  host: "localhost"
  port: 8585
  sslMode: "disable"
  maxIdleConns: 10
  maxOpenConns: 10
newrelic:
  app: offers
  key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
cache:
  maxAgeSeconds: 43200
offersCache:
  maxAgeSeconds: 300
  cleanupInterval: 30
pagination:
  limit: 50
  offset: 0
extensions:
  dogstatsd:
    host: localhost:9125
    prefix: offers.