postgres:
  user: "offers_test"
  dbName: "offers_test"
  host: "localhost"
  port: 0000
  sslMode: "disable"
  maxIdleConns: 10
  maxOpenConns: 10
newrelic:
  app: offers
  key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
